spring.application.name=cyberwatch

# Configuracao de Conexao com o Render
spring.datasource.url=jdbc:postgresql://dpg-d8g1c85ckfvc73e008g0-a.oregon-postgres.render.com:5432/siem?sslmode=require
spring.datasource.username=admin
spring.datasource.password=YU9dUvyIhpIQhw7y1GuYOVuMnlAxXKcd
spring.datasource.driver-class-name=org.postgresql.Driver

# Estrategia de Criacao de Tabelas (DDL)
# 'update' faz o Hibernate criar ou atualizar as tabelas automaticamente na nuvem ao iniciar
spring.jpa.hibernate.ddl-auto=update

# Mostrar comandos SQL no terminal (util para desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect